### ISSUE TITLE
Add empty-state-rename-variant

### ISSUE THREAD

**Issue by redallen** [patternfly/pf-codemods#10]
## empty-state-rename-variant [(#3933)](https://github.com/patternfly/patternfly-react/pull/3933)
- [ ] Variant `small` has been updated to `sm` and variant `large` has been updated to `lg`

**Comment by jenny-s51** [comment]
The changes in [#3933](https://github.com/patternfly/patternfly-react/pull/3933) were [reverted](https://github.com/patternfly/patternfly-react/blob/2e2676ce6bc34f5e20231ca066d26ea4c3ac95e4/packages/react-core/src/components/EmptyState/EmptyState.tsx#L18) -- closing!
