### ISSUE TITLE
crashes when encountering a `<Title>` without `size`

### ISSUE THREAD

**Issue by elad661** [patternfly/pf-codemods#116]
running `pf-codemodes`, it crashes with the message:
```
$ npx pf-codemods ./src
npx: installed 118 in 4.947s
Cannot read property 'value' of undefined
Occurred while linting [filename and line number here]
```
the offending line is
```jsx
<Title headingLevel="h1" className="step-number alert" />
```
adding `size` to the `<Title>` makes the problem go away, but `size` isn't a required prop of `<Title>` so I don't think it should cause a crash.

**Comment by evwilkin** [comment]
Thanks @elad661 for catching this, it looks like the code wasn't accounting for the `size` prop being optional - we just put up PR #117 to get this resolved.

**Comment by evwilkin** [comment]
This change is now live in pf-codemods@1.2.1
