### ISSUE TITLE
Add nav-list-variant

### ISSUE THREAD

**Issue by redallen** [patternfly/pf-codemods#12]
## nav-list-variant [(#4225)](https://github.com/patternfly/patternfly-react/pull/4225)
- [ ] **Nav:** `variant` prop has been removed from `NavList`. Pass variant={`horizontal` | `tertiary`} to `Nav` instead.

**Comment by ddonahue007** [comment]
Two parts to this. (Examples below)

### Part one: (remove NavVariants form imports)
From: 
`import { Nav, NavItem, NavList, NavVariants } from '@patternfly/react-core';`

To:
` import { Nav, NavItem, NavList } from '@patternfly/react-core';`

### Part Two:

From:( move variant from NavList component to Nav component)
```
      <Nav onSelect={this.handleOnSelect}>	      
          <NavList variant={NavVariants.tertiary}>
```
To:
```
        <NavList variant={NavVariants.tertiary}>	        
            <NavList>
```
