### ISSUE TITLE
ResizeObserver - add new function param

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-codemods#137]
Follow up to breaking change PR https://github.com/patternfly/patternfly-react/pull/8324

The `getResizeObserver` function has a new optional third parameter called `useRequestAnimationFrame`, which likely should be  added and defaulted to true for any consumers using the `getResizeObserver` function. 

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

**Comment by nicolethoen** [comment]
@thatblindgeye, since it's optional, will it be okay if we omit this? or will is cause fewer headaches for products to include this update in the code mods?

**Comment by thatblindgeye** [comment]
It might cause less headaches to include it, especially just to inform what the new param does/when it's meant to be `true`.
