### ISSUE TITLE
DropdownMenu - remove deprecated openedOnEnter prop

### ISSUE THREAD

**Issue by evwilkin** [patternfly/pf-codemods#157]
Follow up to breaking change PR https://github.com/patternfly/patternfly-react/pull/8179

The deprecated `openedOnEnter` has been removed from the `DropdownMenu` component and should be removed from consumers' code.

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

**Comment by gitdallas** [comment]
https://github.com/patternfly/pf-codemods/commit/075c1004e49517624bc08b5300bbdd2c001956ce
