### ISSUE TITLE
Modal - api changes to position prop

### ISSUE THREAD

**Issue by tlabaj** [patternfly/pf-codemods#333]
Follow up to breaking change issue https://github.com/patternfly/patternfly-react/issues/8523

position prop has will be change to
position?: 'default' | 'top';

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

**Comment by wise-king-sullyman** [comment]
I'm not sure if a codemod is needed here? The default value of `position` was changed from `undefined` to `'default'`, but that doesn't actually change the behavior from what I can see.

**Comment by wise-king-sullyman** [comment]
@gitdallas @thatblindgeye WDYT?

**Comment by wise-king-sullyman** [comment]
Not needed as https://github.com/patternfly/patternfly-react/issues/8523 didn't actually result in a behavior change.
