### ISSUE TITLE
Alert - remove deprecated titleHeadingLevel prop

### ISSUE THREAD

**Issue by tlabaj** [patternfly/pf-codemods#335]
Follow up to breaking change PR https://github.com/patternfly/patternfly-react/pull/8795

The `titleHeadingLevel` prop has been removed

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

**Comment by adamviktora** [comment]
@tlabaj It looks that this issue was already solved in this PR: https://github.com/patternfly/pf-codemods/pull/277

**Comment by tlabaj** [comment]
@adamviktora Great!    I will close this issue.
