### ISSUE TITLE
Select imports only partially updated

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/pf-codemods#483]
Reported by dan when running in cost management.

the codemods replaced all my Select* imports with this:
`import { Select as SelectDeprecated } from '@patternfly/react-core/deprecated';`
It omitted other objects like `SelectOption`, `SelectVariant`, etc.
I had to add those items back in manually.

also: 
"I don't mind that the import points to the deprecated module, but probably could do without renaming the Select objects"

why we'd decided to do it: 
think we decided to do that for a couple reasons. to encourage updating to the newer version, and to prevent conflict if we are also converting next/Select to be the default

**Comment by gitdallas** [comment]
This one and https://github.com/patternfly/pf-codemods/issues/482 likely share the same source of the issue
