### ISSUE TITLE
class name updater: update `pf-global` variables

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/pf-codemods#515]

**Comment by MariaAga** [comment]
Does this include `$pf-global--font-path, $pf-global--fonticon-path, $pf-global--icon-path, $pf-global--image-path` or should I open a new issue?

**Comment by wise-king-sullyman** [comment]
@MariaAga yes, at least with the fix in my head it will match anything with `pf-global-`. I'll also probably add an update for `pf-theme` as well as that's another issue that was found.
