### ISSUE TITLE
Bug - components imported in the format `<package name>/dist/dynamic/components/<component name>` aren't picked up by the codemods

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/pf-codemods#632]
Components imported in the format `<package name>/dist/dynamic/components/<component name>` aren't picked up by the codemods

Other dynamic paths could also be issues.

This issue should update all of our v6 codemods to apply for dynamic import paths, ideally via a helper or something if possible so that manual changes aren't required in every rule.

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

**Comment by thatblindgeye** [comment]
We should check if the updates made in https://github.com/patternfly/pf-codemods/pull/640 will resolve this

**Comment by wise-king-sullyman** [comment]
Closed as part of #640
