### ISSUE TITLE
alignEnd - running codemods for v6 produces error for using alignEnd

### ISSUE THREAD

**Issue by jessiehuff** [patternfly/pf-codemods#646]
When running the v6 codemods on Quick Starts, I noticed that it updated `alignRight` to `alignEnd` but gave the following error:
```[!] (plugin rpt2) Error: /Users/jhuff/patternfly-quickstarts/packages/module/src/catalog/Toolbar/QuickStartCatalogFilterItems.tsx(76,16): semantic error TS2322: Type '"alignEnd"' is not assignable to type '"alignRight" | "alignLeft"'.```

I had to revert it back to using `alignRight` for now.

**Comment by thatblindgeye** [comment]
Retested running the v6 codemods on quick starts using the latest v6 alphas. I no longer get the error mentioned above after running codemod fixes and `yarn build`. The only error I get is `[!] (plugin rpt2) Error: /Users/eolkowsk/GitHub/PatternFly/patternfly-quickstarts/packages/module/src/QuickStartCatalogPage.tsx(7,3): semantic error TS2305: Module '"@patternfly/react-core"' has no exported member 'Content'.` which should be expected until all applicable PRs for updating Text/TextContent to just Content are merged in all repos.

Will close this for now, but if anyone else notices the original issue mentioned in the original post we can reopen.
