### ISSUE TITLE
Text - replace with Content

### ISSUE THREAD

**Issue by adamviktora** [patternfly/pf-codemods#663]
Follow up to breaking change PRs: https://github.com/patternfly/patternfly-react/pull/10611 and https://github.com/patternfly/patternfly-react/pull/10643

Use Content instead of Text, TextList, TextListItem and TextContent.

```
<Text component="h3"> -> <Content component="h3">
<Text> -> <Content component="p">
<TextContent> -> <Content>
<TextContent isVisited> -> <Content isVisitedLink>
<TextList> -> <Content component="ul">
<TextList isPlain> -> <Content component="ul" isPlainList>
<TextList component="ol"> -> <Content component="ol">
<TextListItem> -> <Content component="li">
<TextListItem component="dt"> -> <Content component="dt">
```

We might want to try:
- if previously wrapped in `<TextContent>` or in `<TextList>`, replace with corresponding simple html element, but ONLY IF there is no specific prop on that component - `isPlain` (TextList), `isVisitedLink` (Text)

_Required actions:_
1. Build codemod
2. Build test
3. Update readme with description & example

**Comment by thatblindgeye** [comment]
https://github.com/patternfly/patternfly-react/pull/10611 is also related
