### ISSUE TITLE
EmptyState - enhance autofixer for when titleText and children are not present

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/pf-codemods#764]
Followup to https://github.com/patternfly/pf-codemods/issues/749. One of the issues found was that if there's no `titleText` or `children` for EmptyStateHeader, the autofixer we currently have doesn't run. We can try to provide an autofixer in this instance (the workaround consumer-side was passing `titleText=""` to EmptyState, which may not be ideal if we want to encourage consumers to pass a valid titleText).

**Comment by kmcfaul** [comment]
Update the current EmptyState codemod to adjust for not requiring titleText anymore
