### ISSUE TITLE
In the pf-codemods README some rules have no fix but do include examples, we should remove those unchanging examples

### ISSUE THREAD

**Issue by wise-king-sullyman** [patternfly/pf-codemods#767]
Per title, we probably don't want rules that aren't making any changes to feature the in/out example blocks, for general clarity reasons and for simplifying release notes based on our README.

**Comment by adamviktora** [comment]
Oh, that's probably my mistake, I'll take the issue.

**Comment by adamviktora** [comment]
So I checked all v6 rules and the only one with this problem is the `tokensWarn` rule, but it was restructured to be a fix in a recent PR https://github.com/patternfly/pf-codemods/pull/763

**Comment by adamviktora** [comment]
@wise-king-sullyman Does it mean we should **delete** the example in/out files? Or removing them from README is sufficient?

**Comment by wise-king-sullyman** [comment]
Removing them from the readme should be sufficient

**Comment by adamviktora** [comment]
I checked again with a script and there are no rules without a fix that would include an example in the `.md` file, so I will close this issue
