### ISSUE TITLE
Investigate if we can run post-codemod cleanup to remove unused imports

### ISSUE THREAD

**Issue by jschuler** [patternfly/pf-codemods#81]
Some of the codemods add imports that may not be used in code, for example `CardHeader`, `CardHeaderMain`, `TabTitleIcon`
<img width="592" alt="Screen Shot 2020-06-04 at 9 05 39 AM" src="https://user-images.githubusercontent.com/869106/83760273-b69cc080-a642-11ea-8a23-64cb5d1d56e8.png">

**Comment by redallen** [comment]
I think adding the `no-unused-imports` rule might help with this

**Comment by redallen** [comment]
This rule solves our problem, but needs to be modified to just run on patternfly imports: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md
